public class Constants {
    String CUSTOMER_DATA_ACCESS = "CUSTOMER_DATA_ACCESS_REQUEST";
    String FLIGHTS_DATA_ACCESS = "CUSTOMER_DATA_ACCESS_REQUEST";
    String EMPLOYEE_DATA_ACCESS = "CUSTOMER_DATA_ACCESS_REQUEST";
}
